//
// Created by Washington on 23/02/2020.
//

#ifndef ENGINE3D_SRC_EVENTS_HPP
#define ENGINE3D_SRC_EVENTS_HPP

enum Events {
    APP_CREATED = 0,
    APP_DESTROYED = 1,
    WINDOW_OPENED = 2,
    WINDOW_POSITION_CHANGED = 3,
    WINDOW_SIZE_CHANGED = 4,
    WINDOW_SIZE_MAXIMIZED = 5,
    WINDOW_SIZE_RESTORED = 6,
    WINDOW_CONTENT_SCALE_CHANGED = 6,
    WINDOW_CLOSED = 7,
    WINDOW_REFRESHED = 8,
    WINDOW_RECEIVED_FOCUS = 9,
    WINDOW_LOST_FOCUS = 10,
    WINDOW_ICONIFY_CHANGED = 11,
    WINDOW_FRAMEBUFFER_SIZE_CHANGED = 12,
    MOUSE_BUTTON_PRESSED = 13,
    MOUSE_BUTTON_RELEASED = 14,
    MOUSE_POSITION_CHANGED = 15,
    MOUSE_ENTERED_WINDOW = 16,
    MOUSE_LEFT_WINDOW = 17,
    SCROLL_CHANGED = 18,
    KEY_PRESSED = 19,
    KEY_RELEASED = 20,
    MONITOR_CONNECTED = 21,
    MONITOR_DISCONNECTED = 22,
    JOYSTICK_CONNECTED = 23,
    JOYSTICK_DISCONNECTED = 24,
    NUM_EVENTS = 25
};

#endif //ENGINE3D_SRC_EVENTS_HPP
